### ISSUE TITLE
Internal Error + Unnecessary overloading

### ISSUE THREAD

**Issue by tetotechy** [geldata/gel#4179]
- EdgeDB Version: 2.0
- OS Version: MacOS

**NOTE: I use DDL, not the CLI tools to modify db schema**

Was following along the EdgeBook, just finished Chapter 9. To align my DB I was populating a migration with the schema included here: https://github.com/edgedb/easy-edgedb/blob/master/chapter9/code.md
Got this error:

```
edgedb error: InternalServerError: 
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/Users/teto/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/server/compiler_pool/worker_proc.py", line 55, in worker
          res = meth(*args)
        File "/Users/teto/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/server/compiler_pool/worker.py", line 185, in compile_in_tx
          units, cstate = COMPILER.compile_in_tx(cstate, *args, **kwargs)
        File "/Users/teto/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 2263, in compile_in_tx
          return self._compile(ctx=ctx, source=source), ctx.state
        File "/Users/teto/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1735, in _compile
          return self._try_compile(ctx=ctx, source=original)
        File "/Users/teto/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1802, in _try_compile
          comp, capabilities = self._compile_dispatch_ql(
        File "/Users/teto/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1668, in _compile_dispatch_ql
          query = self._compile_ql_migration(
        File "/Users/teto/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/server/compiler/compiler.py", line 1074, in _compile_ql_migration
          diff = s_ddl.delta_schemas(
        File "/Users/teto/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/schema/ddl.py", line 326, in delta_schemas
          sd.delta_objects(
        File "/Users/teto/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/schema/delta.py", line 221, in delta_objects
          alter = y.as_alter_delta(
        File "/Users/teto/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/schema/objects.py", line 3081, in as_alter_delta
          delta = super().as_alter_delta(
        File "/Users/teto/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/schema/objects.py", line 1775, in as_alter_delta
          sd.delta_objects(
        File "/Users/teto/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/schema/delta.py", line 221, in delta_objects
          alter = y.as_alter_delta(
        File "/Users/teto/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/schema/objects.py", line 3123, in as_alter_delta
          delta.discard(not_none(delta._get_attribute_set_cmd('ancestors')))
        File "/Users/teto/Library/Application Support/edgedb/portable/2.0/lib/python3.10/site-packages/edb/common/typeutils.py", line 36, in not_none
          assert x is not None
      AssertionError
```

_Don't know whether it is related_: moving properties from object types to their supertypes turns them into `overloaded` in the subtypes (i.e., the object types where they were originallly defined), **even when they have the same types and have no constraints**, and I found no way (via DDL) to "drop" the overloading

**Comment by Dhghomon** [comment]
This one is tough to replicate since you were using DDL but the error looks to be the same as https://github.com/edgedb/edgedb/issues/4303 related to using `overloaded` so your supposition at the end I would think is probably correct.
